apiVersion: v1
kind: Secret
metadata:
  name: openstad-auth-credentials
  namespace: {{ .Release.Namespace }}
data:
  client_id: BASE64ENCODED=
  client_secret: BASE64ENCODED=
  fixed_user_id: BASE64ENCODED=
  fixed_token: BASE64ENCODED=