---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adminer.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.adminer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.adminer.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.adminer.label }}
    spec:
      containers:
      - name: {{ .Values.adminer.deploymentContainer.name }}
        image: {{ .Values.adminer.deploymentContainer.image }}
        ports:
            - name: http
              containerPort: {{ .Values.adminer.deploymentContainer.port }}
        env:
          # DB Reference
          - name: ADMINER_DEFAULT_SERVER
            value: {{ printf "%s-mysql" .Release.Name }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.adminer.deploymentContainer.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.adminer.deploymentContainer.port }}
          initialDelaySeconds: {{ .Values.adminer.probe.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.adminer.probe.liveness.periodSeconds }}

