---
# Previously $gitRoot/k8s/ingress/external.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openstad-{{ .Values.frontend.name }}-ingress
  namespace: {{ .Values.frontend.namespace }}
spec:
  rules:
  - host: www.openstad.softwaredepartment.net
    http:
      paths:
      - backend:
          serviceName: {{ .Values.frontend.name }}-service
          servicePort: {{ .Values.frontend.deploymentContainer.port }}
        path: {{ .Values.frontend.host.path }}
  tls: 
  - hosts:
    - {{ .Values.tls.host }}
    secretName: {{ .Values.tls.secretName }}