---
{{- if .Values.frontend.ingress.enabled -}}
{{ $serviceName := include "openstad.frontend.fullname" . }}
{{ $servicePort := .Values.frontend.service.httpPort }}
{{ $tls := .Values.frontend.ingress.tls }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:

{{- if .Values.frontend.ingress.annotations }}
  annotations:
{{ toYaml .Values.frontend.ingress.annotations | indent 4 }}
{{- end }}

  labels:
  {{- include "openstad.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "openstad.frontend.fullname" . }}-ingress
{{- range $key, $value := .Values.frontend.ingress.extraLabels }}
  {{ $key }}: {{ $value }}
{{- end }}

  name: {{ template "openstad.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  
spec:
  rules:
{{- range $host := .Values.frontend.ingress.hosts }}
    - host: {{ 1 }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end }}
    - host: {{ template "openstad.frontend.url" . }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              
  tls:
    - secretName: {{ .Values.frontend.ingress.tls.secretName }}
      hosts:
        - {{ template "openstad.frontend.url" . }}
  {{- range $value := .Values.frontend.ingress.tls.hosts -}}
        - {{ $value }}
  {{- end -}}

{{- end -}}