---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "openstad.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "openstad.frontend.fullname" . }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.frontend.service.httpPort }}
  - name: management
    port: {{ .Values.frontend.service.managementPort }}
  type: ClusterIP
