---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.imageService.ingName }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.host.www }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.imageService.name }}
          servicePort: {{ .Values.ingress.imageService.containerPort }}
        path: {{ .Values.ingress.imageService.path }}
  tls: 
  - hosts:
    - {{ .Values.tls.host }}
    secretName: {{ .Values.tls.secretName | default "openstad-tls" }}
