---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.image.service.name }}
  namespace: {{ .Values.image.namespace }}
spec:
  selector:
    app: {{ .Values.image.label }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.image.deploymentContainer.port }}
  type: ClusterIP
