---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.auth.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.auth.label }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.auth.deploymentContainer.port }}
  - name: management
    port: 9090
  type: ClusterIP
