---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.apiService.ingName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.define.certManager.clusterIssuer }}
    kubernetes.io/ingress.class: nginx
spec: 
  {{ template "ingressRules" (merge (dict "service" .Values.ingress.apiService) (dict "service" .Values.host)) }}
  tls: 
  - hosts:
    - {{ (printf "*.%s" .Values.host.base) | quote }}
    secretName: {{ .Values.tls.secretName | default "openstad-tls" }}
