---
# Previously $gitRoot/k8s/service/frontend.yaml
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Release.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.deploymentContainer.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.frontend.service.httpPort }}
  - name: management
    port: {{ .Values.frontend.service.managementPort }}
  type: ClusterIP
