---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.api.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.api.label }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.api.service.httpPort }}
  type: ClusterIP
