apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstad-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openstad-api
    spec:
      containers:
      - env:
        - name: APP_HOST
          value: api
        - name: APP_PORT
          value: "8111"
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              key: type
              name: openstad-db-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: openstad-db-credentials
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: openstad-db-credentials
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: hostname
              name: openstad-db-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: hostport
              name: openstad-db-credentials
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: openstad-api-db
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: openstad-api-mail
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: openstad-api-mail
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: openstad-api-mail
        - name: MAIL_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: openstad-api-mail
        - name: MAIL_FROM
          value: Openstad api
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie_secret
              name: openstad-cookies
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt_secret
              name: openstad-cookies
        - name: AUTH_HOST
          value: auth_container
        - name: AUTH_PORT
          value: "4000"
        - name: AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: openstad-auth-credentials
        - name: AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: openstad-auth-credentials
        - name: AUTH_FIXED_TOKEN
          valueFrom:
            secretKeyRef:
              key: fixed_token
              name: openstad-auth-credentials
        - name: AUTH_FIXED_USER_ID
          valueFrom:
            secretKeyRef:
              key: fixed_user_id
              name: openstad-auth-credentials
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: openstad/api:test
        imagePullPolicy: Always
        name: api-container
        command: ['node migrate.js', 'npm start']
        ports:
        - containerPort: 8111
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 500M
      initContainers:
      - args:
        - reset.js
        command:
        - node
        env:
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: hostname
              name: openstad-db-credentials
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: hostport
              name: openstad-db-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: openstad-db-credentials
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: openstad-db-credentials
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: openstad-api-db
        image: openstad/api:test
        imagePullPolicy: Always
        name: init-db-ready
      restartPolicy: Always
