define:
    host-url: &host-url www.openstad.softwaredepartment.net
    host-http: &host-http http://www.openstad.softwaredepartment.net
    host-https: &host-https https://www.openstad.softwaredepartment.net

frontend:
    replicas: 1 # Originally: 1
    namespace: openstad-test # Originally: openstad

    deploymentContainer:
        name: frontend # Originally: frontend
        image: openstad/frontend:debug # Originally: openstad/frontend:debug
        port: 4444 # Originally: 4444

    host:
        www: *host-url
        http: *host-http
        https: *host-https
        path: /

    ingress:
        name: openstad-frontend-ingress # Originally: openstad-frontend-ingress 

    deployment:
        name: frontend # Originally: frontend

    service:
        name: frontend-service # Originally: frontend-service
        httpPort: 8080
        managementPort: 9090

tls:
    host: *host-url
    secretName: openstad-tls
