---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.auth.secretName | default "openstad-auth-db"  }}
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "authDbSecret" . }}