apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodb.secretName }}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "mongodbSecret" . }}
