{{- define "databaseSecret" -}}
  {{ printf "type: %s" (.Values.secrets.database.type | b64enc) }}
  {{ printf "database: %s" (.Values.secrets.database.dbName | b64enc) }}
  {{ printf "hostname: %s" (.Values.secrets.database.hostname | b64enc) }}
  {{ printf "hostport: %s" (.Values.secrets.database.hostport | toString | b64enc) }}
  {{ printf "password: %s" (.Values.secrets.database.password | b64enc) }}
  {{ printf "username: %s" (.Values.secrets.database.username | b64enc) }}
{{- end }}

{{- define "mongodbSecret" -}}
  {{ printf "hostname: %s" (.Values.secrets.mongodb.hostname | b64enc) }}
  {{ printf "hostport: %s" (.Values.secrets.mongodb.hostport | toString | b64enc) }}
  {{ printf "database: %s" (.Values.secrets.mongodb.database | b64enc) }}
{{- end }}

{{- define "cookieSecret" -}}
  {{ printf "cookie_secret: %s" (.Values.secrets.cookies.cookieSecret | b64enc) }}
  {{ printf "jwt_secret: %s" (.Values.secrets.cookies.jwtSecret | b64enc) }}
{{- end }}

{{- define "imageDbSecret" -}}
  {{ printf "database: %s" (.Values.secrets.database.image.dbName | b64enc) }}
{{- end }}

{{- define "apiDbSecret" -}}
  {{ printf "database: %s" (.Values.secrets.database.api.dbName | b64enc) }}
{{- end }}

{{- define "hostsSecret" -}}
  {{ printf "api: %s" (.Values.secrets.hosts.api | b64enc) }}
  {{ printf "auth: %s" (.Values.secrets.hosts.auth | b64enc) }}
  {{ printf "frontend: %s" (.Values.secrets.hosts.frontend | b64enc) }}
  {{ printf "image: %s" (.Values.secrets.hosts.image | b64enc) }}
{{- end }}