---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-api-mail
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  host: {{ .Values.secrets.mail.api.host | default "mail.example.com" | b64enc }}
  port: {{ .Values.secrets.mail.api.port | default 587 | toString | b64enc }}
  user: {{ .Values.secrets.mail.api.user | default "user@example.com" | b64enc }}
  email_from: {{ .Values.secrets.mail.api.emailFrom | default "user@example.com" | b64enc }}
  admin_email_from: {{ .Values.secrets.mail.api.adminEmailFrom | default "admin-user@example.com" | b64enc }}
  password: {{ .Values.secrets.mail.api.password | default ( randAlphaNum 12 ) | b64enc }}
  require_ssl: {{ .Values.secrets.mail.api.requireSsl | default "true" | b64enc }}