---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-auth-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  client_id: {{ .Values.secrets.database.auth.credentials.clientId | default "clientID" | b64enc }}
  client_secret: {{ .Values.secrets.database.auth.credentials.clientSecret | default ( randAlphaNum 12 | quote ) | b64enc }}
  first_login_token: {{ .Values.secrets.database.auth.credentials.firstLoginToken | default "OPENSTAD_ADMIN" | b64enc }}
  fixed_user_id: {{ .Values.secrets.database.auth.credentials.fixedUserId | default 2 | toString | b64enc }}
  fixed_token: {{ .Values.secrets.database.auth.credentials.fixedToken | default ( randAlphaNum 12 | quote ) | b64enc }}
  admin_client_id: {{ .Values.secrets.database.auth.credentials.adminClientId | default "clientID" | b64enc }}
  admin_client_secret: {{ .Values.secrets.database.auth.credentials.adminClientSecret | default ( randAlphaNum 12 | quote ) | b64enc }}
