---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-db-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  type: {{ .Values.secrets.database.type | default "mysql" | b64enc }}
  database: {{ .Values.secrets.database.dbName | default "mysql" | b64enc }}
  hostname: {{ .Values.secrets.database.hostname | default (printf "%s-mysql.%s.svc.cluster.local" .Release.Name .Release.Namespace) | b64enc }}
  hostport: {{ .Values.secrets.database.hostport | default 3306 | toString | b64enc }}
  password: {{ .Values.mysql.db.password | default ( randAlphaNum 12 ) | b64enc }}
  username: {{ .Values.secrets.database.username | default "openstad" | b64enc }}

