---
{{ if .Values.dependencies.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "mysql-secret"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  mysql-root-password: {{ .Values.secrets.database.rootPassword | default ( randAlphaNum 12 ) | b64enc }}
  mysql-replication-password: {{ .Values.secrets.database.replicationPassword | default ( randAlphaNum 12 ) | b64enc }}
  mysql-password: {{ .Values.mysql.db.password | default ( randAlphaNum 12 ) | b64enc }}
{{ end }}
